services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: dev
    restart: always

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    ports:
      - 8000:8000

    networks:
      - backend_network

    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M
        reservations:
          cpus: '0.2'
          memory: 512M

  redis_worker:
    container_name: redis_worker
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: dev
    restart: always
    command: ["python", "src/redis_worker.py"]

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - backend_network

    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M
        reservations:
          cpus: '0.2'
          memory: 512M

  db:
    container_name: db
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    ports:
      - 127.0.0.1:5432:5432

    volumes:
      - cust_dev_ai_pg_data:/var/lib/postgresql/data

    networks:
      - backend_network

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped

    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    ports:
      - 127.0.0.1:6379:6379

    networks:
      - backend_network

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M

networks:
  backend_network:
    driver: bridge

volumes:
  cust_dev_ai_pg_data:
    driver: local
