from typing import Any, List

from langgraph.graph import END, START
from langgraph.types import Send

from src.configs.log.logger import get_logger
from src.domains.persona.infrastructure.graph.generate_single_persona import (
    GenerateSinglePersonaGraph,
)
from src.domains.persona.infrastructure.graph.graph_utils import (
    get_person_count,
    get_segment_description,
    get_segment_name,
)
from src.domains.persona.infrastructure.prompt.prompt_manager import (
    PersonaPromptManager,
)
from src.domains.persona.schemas.generate_persona import (
    BaseInputData,
    GeneratePersonaSchema,
    GeneratePersonasSchema,
)
from src.infrastructure.graph.base_graph import BaseGraph


class GeneratePersonasGraph(BaseGraph):

    _prompt_builder: PersonaPromptManager

    def __init__(self, sub_graph: GenerateSinglePersonaGraph, **kwargs: Any) -> None:
        """Initialize the graph with the necessary components."""
        self._sub_graph_generate_single_persona = sub_graph

        super().__init__(
            state_schema=GeneratePersonasSchema,
            output_schema=self._sub_graph_generate_single_persona.output_schema,
            **kwargs,
        )
        self._logger = get_logger(f"{__name__}.{self.__class__.__name__}")

    def _configurate_graph(self) -> None:
        self.add_node("generate_single_persona", self._sub_graph_generate_single_persona.graph)

        self.add_conditional_edges(START, self._map_personas, ["generate_single_persona"])
        self.add_edge("generate_single_persona", END)

    async def _map_personas(self, state: GeneratePersonasSchema) -> List[Send]:

        count = get_person_count(state)

        segment_name = get_segment_name(state)
        segment_description = get_segment_description(state)

        return [
            Send(
                "generate_single_persona",
                GeneratePersonaSchema(
                    input_data=BaseInputData(segment_name=segment_name, segment_description=segment_description),
                    demographic_attributes=None,  # This will be generated by the sub-graph
                    biography=None,  # This will be generated by the sub-graph
                    experiences=None,  # This will be generated by the sub-graph
                ),
            )
            for _ in range(count)
        ]
